<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wynil.Core\Wynil.Core.csproj" />
    <ProjectReference Include="..\Wynil.Media\Wynil.Media.csproj" />
    <ProjectReference Include="..\Wynil.Settings\Wynil.Settings.csproj" />
    <ProjectReference Include="..\Wynil.Wallpaper\Wynil.Wallpaper.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Resource Include="..\..\assets\logo.png">
      <Link>Assets\logo.png</Link>
    </Resource>
    <Content Include="..\Wynil.Frontend\dist\**\*">
      <Link>Frontend\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
