<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NowSpinning.Core\NowSpinning.Core.csproj" />
    <ProjectReference Include="..\NowSpinning.Media\NowSpinning.Media.csproj" />
    <ProjectReference Include="..\NowSpinning.Settings\NowSpinning.Settings.csproj" />
    <ProjectReference Include="..\NowSpinning.Wallpaper\NowSpinning.Wallpaper.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Content Include="..\NowSpinning.Frontend\dist\**\*">
      <Link>Frontend\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
